#!/bin/bash
# credit to budlabs https://www.youtube.com/@dubbeltumme

SCRIPT_FOLDER="$HOME/docs/my_scripts/"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"

if [[ -f $SCRIPT_FILE ]]; then
	echo file already exists
else
	echo '#!/bin/bash' > $SCRIPT_FILE
	chmod +x $SCRIPT_FILE
fi

$EDITOR $SCRIPT_FILE
