#!/bin/bash
rclone copy /home/kab/docs/game_dev/games/godot main:godot
rclone copy /home/kab/docs/game_dev/music/music_50_perc/lmms/ main:lmms
rclone copy /home/kab/docs/game_dev/art/art_50_perc/ main:art

