#!/bin/bash
echo "logging pomodoro $1 minutes at $(date +"%H:%M")
"
# the line is the day of the year +1
line_no=$(($(date +%j) + 1))
line=$(sed -n "${line_no}p" < "$pomo_measure" )
# today=$(date +"%a %d %b %Y")

# search last date if it is today
# append to second column time + time
# add to third column total qalc
col2=$(echo "$line" | awk -F "," '{print $2}')+$1
col3=$(qalc -t "$(echo "$line" | awk -F "," '{print $2}') + $1")
sed -i "${line_no}d" "$pomo_measure"
# new_line=$(echo "$(date +"%a %d %b %Y")	${col2}	${col3}")
new_line=$(date +"%a %d %b %Y,${col2},${col3}")
echo "$new_line"
sed -i "${line_no}i ${new_line}" "$pomo_measure"
