#!/bin/bash
source /home/kab/applications/pomo/pomo_config.sh
clock=$(/home/kab/applications/pomo/pomo.sh clock)
pomo_measure=${HOME}/docs/measures/pomo/2026.csv

# if we are on a break, then no need to add break time to pomodoro
if [[ $clock =~ "B" ]]; then
	/home/kab/applications/pomo/pomo.sh stop
	exit 0;
fi

time_left=$(echo $clock|sed "s/^W\([0-9].\).*$/\1/g")
time_spent=$(qalc -t "$POMO_WORK_TIME - $time_left")
# echo "$time_left"

pomo_log "$time_spent"

/home/kab/applications/pomo/pomo.sh stop
echo "pomo_exit_save executed!" >> /tmp/trap_test.log
